gateways:
- smartcon
hosts:
- smartcon-model.kubecon.demo.vamp.cloud
routes:
- protocol: http
  weights:
  - destination: smartcon-model-destination
    port: 5001
    version: smartcon-model-v1
    weight: 50
  - destination: smartcon-model-destination
    port: 5001
    version: smartcon-model-v2
    weight: 50