apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcon-app-v1.0
  namespace: smartcon
  labels:
    app: smartcon-app
    version: v1.0
    deployment: smartcon-app-v1.0
spec:
  selector:
    matchLabels:
      app: smartcon-app
      version: v1.0
  replicas: 1
  template:
    metadata:
      name: smartcon-app-v1.0
      labels:
        app: smartcon-app
        version: v1.0
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
    spec:
      containers:
      - name: smartcon-app
        image: magneticio/smartcon-app:1.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcon-app-v2.0
  namespace: smartcon
  labels:
    app: smartcon-app
    version: v2.0
    deployment: smartcon-app-v2.0
spec:
  selector:
    matchLabels:
      app: smartcon-app
      version: v2.0
  replicas: 1
  template:
    metadata:
      name: smartcon-app-v2.0
      labels:
        app: smartcon-app
        version: v2.0
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
    spec:
      containers:
      - name: smartcon-app
        image: magneticio/smartcon-app:2.0
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
        env:
        - name: DISCOVER_URL
          value: http://smartcon-model.smartcon.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcon-model-v1.0
  namespace: smartcon
  labels:
    app: smartcon-model
    version: v1.0
    deployment: smartcon-model-v1.0
spec:
  selector:
    matchLabels:
      app: smartcon-model
      version: v1.0
  replicas: 1
  template:
    metadata:
      name: smartcon-model-v1.0
      labels:
        app: smartcon-model
        version: v1.0
    spec:
      containers:
      - name: smartcon-model
        image: magneticio/smartcon-model
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        env:
        - name: VERSION
          value: "1.0"