application: smartcon-app
ports:
- name: http
  port: 5000
  protocol: TCP
  targetPort: 5000
subsets:
  smartcon-app-v1:
    labels:
      version: v1.0
  smartcon-app-v2:
    labels:
      version: v2.0