apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcon-app-v1.0
  namespace: smartcon
  labels:
    app: smartcon-app
    version: v1.0
    deployment: smartcon-app-v1.0
spec:
  selector:
    matchLabels:
      app: smartcon-app
      version: v1.0
  replicas: 1
  template:
    metadata:
      name: smartcon-app-v1.0
      labels:
        app: smartcon-app
        version: v1.0
    spec:
      containers:
      - name: smartcon-app
        image: magneticio/smartcon-app:1.0
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15